FoxLakeRentals/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views
from .views import PostListView, detailPostView, createPostView

urlpatterns = [
    path('post/', createPostView, name='posts-create'),
    path('', PostListView.as_view(), name='posts-home'),
    ]

posts/models.py
from django.db import models
from django.conf import settings
from PIL import Image
# Create your models here.
class Post(models.Model):
  title = models.CharField(max_length=250)
  description = models.TextField()
  available = models.BooleanField(default=True)
  rate = models.IntegerField()
  posted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class PostImage(models.Model):
  post = models.ForeignKey(Post, default=None, on_delete=models.CASCADE)
  image = models.ImageField(upload_to='post_images')

  def save(self, *args, **kwargs):
    super().save(*args, **kwargs)

    img = Image.open(self.image.path)

    if img.width > 500 or img.height > 500:
      new_size = (500, 500)
      img.thumbnail(new_size)
      img.save(self.image.path)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.utils import timezone
from .managers import CustomUserManager
# Create your models here.

class CustomUser(AbstractBaseUser,PermissionsMixin):
  email = models.EmailField(unique=True)
  phone = models.IntegerField(unique=True)
  is_staff = models.BooleanField(default=False)
  is_active = models.BooleanField(default=True)
  date_joined = models.DateTimeField(default=timezone.now)

  USERNAME_FIELD = 'email'
  REQUIRED_FIELDS = ['phone']

  objects = CustomUserManager()

posts/forms.py
from django import forms 
from .models import Post, PostImage

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'description', 'rate',)

class PostImageForm(forms.ModelForm):
    class Meta:
        model = PostImage
        fields = ('image',)
    
    

users/forms.py
from django.contrib.auth.forms import UserCreationFrom, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationFrom):
  class meta(UserCreationFrom):
    model = CustomUser
    fields = ['email', 'phone', 'password1', 'password2']

class CustomUserChangeForm(UserChangeForm):
  class meta(UserChangeForm):
    model = CustomUser
    fields = ['email', 'phone']

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.forms import modelformset_factory
from django.contrib import messages
from .models import Post, PostImage
from .forms import PostForm, PostImageForm

# Create your views here.

class PostListView(ListView):
    model = Post
    template_name = 'posts/home.html'
    context_object_name = 'posts'

def detailPostView(request, id):
  post = get_object_or_404(Post, id)
  photos = PostImage.objects.filter(post=post)
  return render(request, 'post-detail', {'photos':photos, 'post':post})

@login_required
def createPostView(request):

  ImageFormSet = modelformset_factory(PostImage, form=PostImageForm, extra=5)

  if request.method == 'POST':
    postForm = PostForm(request.POST)
    formset = ImageFormSet(request.POST, request.FILES, queryset=PostImage.objects.none())

    if postForm.is_valid() and formset.is_valid():
      post_form = postForm.save(commit=False)
      post_form.posted_by = request.user
      post_form.save()

      for form in formset.cleaned_data:
        if form:
          image = form['image']
          photo = PostImage(post=post_form, image=image)
          photo.save()
      messages.success(request, "Posting crated!")
      return redirect('posts-home')

    else:
      messages.error(postForm.errors, formset.errors)
  else:
    postForm = PostForm()
    formset = ImageFormSet(queryset=PostImage.objects.none())

  return render(request, 'posts/post_create.html', {'postForm':postForm, 'formset':formset})

posts/templates/posts/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Fox Lake Rentals</title>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#" style="padding-left:100px">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#" style="padding-left:100px">Link</a>
            </li>
          </ul>
        </div>
      </div>
      </nav>
    </header>
    <main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}
      </div>
    </div>
    </main>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

posts/templates/posts/home.html
{% extends 'posts/base.html' %}
{% block content %}
  {% if posts %}
    {% for post in posts %}
      <h1>{{post.title}}</h1>
      <img src="{{post.postimage_set.first.image.url}}">
    {% endfor %}
  {% else %}
    <h1>No Posts Yet!</h1>
  {% endif %}
{% endblock content %}

posts/templates/posts/post_create.html
{% extends 'posts/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
   <form method="post" enctype="multipart/form-data">
     {% csrf_token %}
     {{postForm|crispy}}
     {{formset|crispy}}
     <button type="submit">Post</button>
   </form>
{% endblock content %} 